### PR TITLE
update package and disable warning message

### PR DESCRIPTION
**Pull request by adamjanin**
officially the warning messages will be removed on v6. For now, we can only disable from configuration.

### CODE REVIEW

**Comment by rohaizanr** [comment]
@adamjanin 

ada error ni time npm install

```
'Log files:
/Users/rohaizan/.npm/_logs/2024-04-30T19_40_36_841Z-debug-0.log

# npm resolution error report

While resolving: e-masjid-dashboard@1.0.0
Found: react@18.3.1
node_modules/react
  react@"^18.2.0" from the root project
  peer react@">=17" from @coreui/icons-react@2.2.1
  node_modules/@coreui/icons-react
    @coreui/icons-react@"^2.1.0" from the root project
  peer react@"^18.3.1" from react-dom@18.3.1
  node_modules/react-dom
    react-dom@"^18.2.0" from the root project
    peer react-dom@">=17" from @coreui/icons-react@2.2.1
    node_modules/@coreui/icons-react
      @coreui/icons-react@"^2.1.0" from the root project
    peer react-dom@">=17" from @coreui/react@4.11.1
    node_modules/@coreui/react
      @coreui/react@"^4.9.0-rc.0" from the root project
    peer react-dom@">=17" from @coreui/react-chartjs@2.1.3
    node_modules/@coreui/react-chartjs
      @coreui/react-chartjs@"^2.1.3" from the root project
    peer react-dom@">=16.8.0" from react-colorful@5.6.1
    node_modules/react-colorful
      react-colorful@"^5.6.1" from the root project
    peer react-dom@">= 16.8.0" from styled-components@5.3.11
    node_modules/styled-components
      styled-components@"^5.3.11" from the root project
      peer styled-components@">= 5.0.0" from react-data-table-component@7.6.2
      node_modules/react-data-table-component
        react-data-table-component@"^7.5.4" from the root project
    peer react-dom@"^16.9.0 || ^17 || ^18" from react-datepicker@4.25.0
    node_modules/react-datepicker
      react-datepicker@"^4.21.0" from the root project
  peer react@">=17" from @coreui/react@4.11.1
  node_modules/@coreui/react
    @coreui/react@"^4.9.0-rc.0" from the root project
  peer react@">=17" from @coreui/react-chartjs@2.1.3
  node_modules/@coreui/react-chartjs
    @coreui/react-chartjs@"^2.1.3" from the root project
  peer react@"*" from react-color@2.19.3
  node_modules/react-color
    react-color@"^2.19.3" from the root project
  peer react@">=16.8.0" from react-colorful@5.6.1
  node_modules/react-colorful
    react-colorful@"^5.6.1" from the root project
  peer react@">= 16.8.3" from react-data-table-component@7.6.2
  node_modules/react-data-table-component
    react-data-table-component@"^7.5.4" from the root project
  peer react@">= 16.8.0" from styled-components@5.3.11
  node_modules/styled-components
    styled-components@"^5.3.11" from the root project
    peer styled-components@">= 5.0.0" from react-data-table-component@7.6.2
    node_modules/react-data-table-component
      react-data-table-component@"^7.5.4" from the root project
  peer react@"^16.9.0 || ^17 || ^18" from react-datepicker@4.25.0
  node_modules/react-datepicker
    react-datepicker@"^4.21.0" from the root project
  peer react@">=0.14.0" from react-imask@7.6.0
  node_modules/react-imask
    react-imask@"^7.1.3" from the root project

Could not resolve dependency:
react-qr-code@"^2.0.12" from the root project

Conflicting peer dependency: react@18.2.0
node_modules/react
  peer react@"18.2.0" from react-native@0.74.0
  node_modules/react-native
    peer react-native@"*" from react-native-svg@15.2.0
    node_modules/react-native-svg
      peerOptional react-native-svg@"*" from react-qr-code@2.0.12
      node_modules/react-qr-code
        react-qr-code@"^2.0.12" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

verify jap

**Comment by adamjanin** [comment]
@rohaizanr , boleh tahu ke kalau run command "sh run-dev.sh" masih ada error juga?

**Comment by rohaizanr** [comment]
Ya, sama

**Comment by adamjanin** [comment]
rasanya ada masalah dgn npm cache ni
boleh cuba command ni `npm cache clean --force `
so far run dekat docker-compose ok ja.
image

**Comment by rohaizanr** [comment]
@adamjanin  .... hmmmm sama gak. Mac punya issue ke ni

**Comment by rohaizanr** [comment]
@adamjanin https://github.com/hisyamnasir/e-masjid.my/tree/vite-ts-dashboard dah push. error ni dah takde. rasanya boleh cancel PR ni

**Pull request closed without merging**
