### PR TITLE
First version, 6 background templates. #81

### PR DESCRIPTION
**Pull request by lurhays**
Please review.

### CODE REVIEW

**Comment by rohaizanr** [comment]
@lurhays

ada beberapa comments untuk 'first version'

1. Doublekan size QR code
2. Gunakan 'rounded-corners' untuk Textbox Masjid di bahagian bawah 
3. Tukarkan text 'Style' ke 'Latar belakang'
4. Missing bahagian step 1-2-3-4 
Screenshot 2024-02-19 at 12 45 04 AM

**Comment by lurhays** [comment]
Updated. Details at https://github.com/Dev4w4n/e-masjid.my/issues/81#issuecomment-1952221570

**Comment by rohaizanr** [comment]
it's a very nice

**Review by Dev4w4n — APPROVED** [review]
terima kasih

**Pull request merged**
